/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    bookings: Booking;
    properties: Property;
    seasons: Season;
    'blocked-dates': BlockedDate;
    'ical-feeds': IcalFeed;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    'blocked-dates': BlockedDatesSelect<false> | BlockedDatesSelect<true>;
    'ical-feeds': IcalFeedsSelect<false> | IcalFeedsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Korisnici koji mogu pristupiti admin panelu
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  role: 'super-admin' | 'manager';
  phone?: string | null;
  /**
   * Odaberi koje nekretnine ovaj manager moze uredivati
   */
  managedProperties?: (number | Property)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Vile, apartmani i druge nekretnine za najam
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  /**
   * Samo "Aktivna" nekretnina se prikazuje na stranici
   */
  status: 'draft' | 'active' | 'paused' | 'archived';
  name: string;
  /**
   * Koristi se u URL-u: /properties/villa-adriatica
   */
  slug: string;
  type: 'villa' | 'apartment' | 'house' | 'studio' | 'penthouse';
  /**
   * Prikazuje se na karticama i u pretrazi. Max 200 znakova.
   */
  shortDescription: string;
  /**
   * Detaljan opis nekretnine za stranicu
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Ukupan kapacitet
   */
  maxGuests: number;
  bedrooms: number;
  beds: number;
  bathrooms: number;
  sizeM2?: number | null;
  /**
   * Za vile s okućnicom
   */
  plotSizeM2?: number | null;
  address: {
    street?: string | null;
    city: string;
    postalCode?: string | null;
    region?: string | null;
    country: string;
  };
  /**
   * Za prikaz na karti
   */
  coordinates?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  /**
   * npr. Plaža 500m, Centar grada 2km, Zračna luka 45km
   */
  distances?:
    | {
        place: string;
        distance: string;
        id?: string | null;
      }[]
    | null;
  amenities?: {
    outdoor?: {
      pool?: boolean | null;
      poolHeated?: boolean | null;
      jacuzzi?: boolean | null;
      garden?: boolean | null;
      terrace?: boolean | null;
      bbq?: boolean | null;
      outdoorDining?: boolean | null;
      parking?: boolean | null;
    };
    wellness?: {
      sauna?: boolean | null;
      steamBath?: boolean | null;
      gym?: boolean | null;
      massageRoom?: boolean | null;
    };
    indoor?: {
      wifi?: boolean | null;
      airConditioning?: boolean | null;
      heating?: boolean | null;
      fireplace?: boolean | null;
      tv?: boolean | null;
      satelliteTV?: boolean | null;
      netflix?: boolean | null;
      soundSystem?: boolean | null;
    };
    kitchen?: {
      fullKitchen?: boolean | null;
      dishwasher?: boolean | null;
      washingMachine?: boolean | null;
      dryer?: boolean | null;
      coffeeMachine?: boolean | null;
      oven?: boolean | null;
      microwave?: boolean | null;
      freezer?: boolean | null;
    };
    additional?: {
      petsAllowed?: boolean | null;
      smokingAllowed?: boolean | null;
      wheelchairAccessible?: boolean | null;
      evCharger?: boolean | null;
      babyFriendly?: boolean | null;
      workDesk?: boolean | null;
      bicycles?: boolean | null;
      kayaks?: boolean | null;
    };
  };
  /**
   * Jedinstvene karakteristike koje izdvajaju nekretninu
   */
  specialFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  rules: {
    checkInTime: string;
    checkOutTime: string;
    /**
     * Zadano (sezone mogu imati svoje)
     */
    minStay?: number | null;
    maxStay?: number | null;
    houseRules?: string | null;
  };
  seo?: {
    /**
     * Naslov u Google rezultatima. Max 60 znakova.
     */
    metaTitle?: string | null;
    /**
     * Opis u Google rezultatima. Max 160 znakova.
     */
    metaDescription?: string | null;
  };
  /**
   * Prikazuje se kao thumbnail u listama
   */
  featuredImage: number | Media;
  /**
   * Dodatne slike za galeriju
   */
  gallery?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Slike i mediji za stranicu
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Opis slike za SEO i čitače ekrana. Npr: "Pogled na bazen iz dnevnog boravka"
   */
  alt: string;
  /**
   * Pomaže organizirati galeriju na stranici
   */
  category:
    | 'exterior'
    | 'interior'
    | 'pool-wellness'
    | 'bedrooms'
    | 'kitchen-dining'
    | 'bathroom'
    | 'garden'
    | 'view'
    | 'surroundings';
  /**
   * Ostavite prazno za globalne slike (logo, pozadine...)
   */
  property?: (number | null) | Property;
  /**
   * Manji broj = prije se prikazuje. 0, 1, 2, 3...
   */
  sortOrder?: number | null;
  /**
   * Istaknuta slika se koristi kao glavna slika nekretnine
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Sve rezervacije nekretnina
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  /**
   * Automatski generiran
   */
  bookingNumber: string;
  property: number | Property;
  status: 'pending' | 'deposit-paid' | 'fully-paid' | 'checked-in' | 'completed' | 'cancelled' | 'no-show';
  guestFirstName: string;
  guestLastName: string;
  guestName?: string | null;
  guestEmail: string;
  guestPhone: string;
  guestCountry?: string | null;
  guestLanguage?: ('hr' | 'en' | 'de' | 'it') | null;
  checkIn: string;
  checkOut: string;
  numberOfGuests: number;
  numberOfChildren?: number | null;
  /**
   * Automatski izračunato
   */
  numberOfNights?: number | null;
  specialRequests?: string | null;
  estimatedArrivalTime?: string | null;
  /**
   * Detaljan pregled cijene
   */
  priceBreakdown?: {
    /**
     * Automatski generirano iz sezona
     */
    nightlyRates?:
      | {
          date?: string | null;
          price?: number | null;
          isWeekend?: boolean | null;
          id?: string | null;
        }[]
      | null;
    accommodationTotal?: number | null;
    cleaningFee?: number | null;
    extras?:
      | {
          description?: string | null;
          amount?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  paymentDetails: {
    /**
     * Ukupan iznos rezervacije
     */
    totalPrice: number;
    /**
     * Koliki postotak se plaća odmah
     */
    depositPercentage?: number | null;
    /**
     * Plaća se pri rezervaciji
     */
    depositAmount?: number | null;
    /**
     * Plaća se prije dolaska
     */
    remainingAmount?: number | null;
    /**
     * Automatski: 14 dana prije check-in
     */
    remainingDueDate?: string | null;
  };
  paymentStatus: 'unpaid' | 'deposit-paid' | 'fully-paid' | 'partial-refund' | 'full-refund';
  /**
   * Automatski popunjeno nakon plaćanja
   */
  stripeData?: {
    depositPaymentIntent?: string | null;
    depositPaidAt?: string | null;
    remainingPaymentIntent?: string | null;
    remainingPaidAt?: string | null;
  };
  /**
   * Samo za osoblje, gost ne vidi
   */
  internalNotes?: string | null;
  source?: ('direct' | 'phone' | 'email' | 'returning' | 'referral') | null;
  cancellation?: {
    cancelledAt?: string | null;
    cancelledBy?: ('guest' | 'owner' | 'system') | null;
    cancellationReason?: string | null;
    refundAmount?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Sezone i cijene za nekretnine
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  /**
   * Za koju nekretninu vrijedi ova sezona
   */
  property: number | Property;
  /**
   * Interno ime za lakše snalaženje
   */
  name: string;
  /**
   * Pomaže kategorizirati sezone
   */
  type: 'high' | 'mid' | 'low' | 'holiday' | 'special';
  startDate: string;
  endDate: string;
  pricing: {
    /**
     * Bazna cijena za običan dan (pon-čet)
     */
    pricePerNight: number;
    /**
     * Petak i subota mogu imati višu cijenu
     */
    weekendPricing?: {
      /**
       * Ako nije aktivno, vikend ima istu cijenu kao i ostali dani
       */
      enabled?: boolean | null;
      fridayPrice?: number | null;
      saturdayPrice?: number | null;
      /**
       * Umjesto fiksne vikend cijene, dodaj postotak na baznu cijenu
       */
      usePercentage?: boolean | null;
      /**
       * npr. 20 = bazna cijena + 20%
       */
      weekendPercentage?: number | null;
    };
    /**
     * Jednokratna naknada po rezervaciji. 0 = nema naknade.
     */
    cleaningFee?: number | null;
  };
  stayRules?: {
    /**
     * Minimum dana za rezervaciju
     */
    minStay?: number | null;
    maxStay?: number | null;
    /**
     * Ostavi sve odabrano za bilo koji dan. U visokoj sezoni možda samo subota.
     */
    allowedCheckInDays?: ('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[] | null;
  };
  /**
   * HEX boja za prikaz u kalendaru
   */
  color?: string | null;
  /**
   * Neaktivne sezone se ignoriraju pri izračunu cijena
   */
  isActive?: boolean | null;
  /**
   * Samo za internu upotrebu, gosti ne vide
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Datumi kada nekretnina nije dostupna za rezervaciju
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-dates".
 */
export interface BlockedDate {
  id: number;
  property: number | Property;
  startDate: string;
  endDate: string;
  /**
   * Odakle dolazi ova blokada
   */
  source: 'manual' | 'booking-com' | 'airbnb' | 'vrbo' | 'ical-other';
  reason: 'owner-use' | 'maintenance' | 'external-booking' | 'cleaning' | 'other';
  /**
   * Interne napomene
   */
  notes?: string | null;
  /**
   * Automatski popunjeno kod iCal importa
   */
  icalData?: {
    /**
     * Jedinstveni ID iz iCal feeda
     */
    uid?: string | null;
    /**
     * Naslov iz iCal eventa
     */
    summary?: string | null;
    lastSynced?: string | null;
  };
  /**
   * Neaktivne blokade se ignoriraju
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sinkronizacija kalendara s Booking.com, Airbnb i drugim platformama
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ical-feeds".
 */
export interface IcalFeed {
  id: number;
  /**
   * Za koju nekretninu je ovaj feed
   */
  property: number | Property;
  /**
   * Neaktivni feedovi se ne sinkroniziraju
   */
  isActive?: boolean | null;
  name: string;
  platform: 'booking-com' | 'airbnb' | 'vrbo' | 'google' | 'other';
  /**
   * Import = dohvaćamo njihove rezervacije. Export = oni dohvaćaju naše.
   */
  direction: 'import' | 'export' | 'both';
  importSettings?: {
    /**
     * URL koji dohvaćamo za uvoz rezervacija
     */
    importUrl?: string | null;
    syncFrequency?: ('15min' | '30min' | 'hourly' | '2hours' | '6hours' | 'daily') | null;
    /**
     * Automatski kreira BlockedDates za uvezene rezervacije
     */
    autoBlockDates?: boolean | null;
  };
  exportSettings?: {
    /**
     * Ovaj URL daš platformi za uvoz naših rezervacija. Automatski generiran.
     */
    exportUrl?: string | null;
    /**
     * Eksportira i ručno blokirane datume, ne samo rezervacije
     */
    includeBlockedDates?: boolean | null;
    /**
     * Dodaj dan prije i poslije svake rezervacije (za čišćenje)
     */
    includeBuffer?: boolean | null;
  };
  /**
   * Automatski ažurirano
   */
  syncStatus?: {
    lastSync?: string | null;
    lastSyncStatus?: ('success' | 'error' | 'in-progress' | 'never') | null;
    lastSyncError?: string | null;
    /**
     * Ukupan broj uvezenih rezervacija
     */
    eventsImported?: number | null;
  };
  /**
   * Interne napomene
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'blocked-dates';
        value: number | BlockedDate;
      } | null)
    | ({
        relationTo: 'ical-feeds';
        value: number | IcalFeed;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  phone?: T;
  managedProperties?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  category?: T;
  property?: T;
  sortOrder?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  bookingNumber?: T;
  property?: T;
  status?: T;
  guestFirstName?: T;
  guestLastName?: T;
  guestName?: T;
  guestEmail?: T;
  guestPhone?: T;
  guestCountry?: T;
  guestLanguage?: T;
  checkIn?: T;
  checkOut?: T;
  numberOfGuests?: T;
  numberOfChildren?: T;
  numberOfNights?: T;
  specialRequests?: T;
  estimatedArrivalTime?: T;
  priceBreakdown?:
    | T
    | {
        nightlyRates?:
          | T
          | {
              date?: T;
              price?: T;
              isWeekend?: T;
              id?: T;
            };
        accommodationTotal?: T;
        cleaningFee?: T;
        extras?:
          | T
          | {
              description?: T;
              amount?: T;
              id?: T;
            };
      };
  paymentDetails?:
    | T
    | {
        totalPrice?: T;
        depositPercentage?: T;
        depositAmount?: T;
        remainingAmount?: T;
        remainingDueDate?: T;
      };
  paymentStatus?: T;
  stripeData?:
    | T
    | {
        depositPaymentIntent?: T;
        depositPaidAt?: T;
        remainingPaymentIntent?: T;
        remainingPaidAt?: T;
      };
  internalNotes?: T;
  source?: T;
  cancellation?:
    | T
    | {
        cancelledAt?: T;
        cancelledBy?: T;
        cancellationReason?: T;
        refundAmount?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  status?: T;
  name?: T;
  slug?: T;
  type?: T;
  shortDescription?: T;
  description?: T;
  maxGuests?: T;
  bedrooms?: T;
  beds?: T;
  bathrooms?: T;
  sizeM2?: T;
  plotSizeM2?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        region?: T;
        country?: T;
      };
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  distances?:
    | T
    | {
        place?: T;
        distance?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        outdoor?:
          | T
          | {
              pool?: T;
              poolHeated?: T;
              jacuzzi?: T;
              garden?: T;
              terrace?: T;
              bbq?: T;
              outdoorDining?: T;
              parking?: T;
            };
        wellness?:
          | T
          | {
              sauna?: T;
              steamBath?: T;
              gym?: T;
              massageRoom?: T;
            };
        indoor?:
          | T
          | {
              wifi?: T;
              airConditioning?: T;
              heating?: T;
              fireplace?: T;
              tv?: T;
              satelliteTV?: T;
              netflix?: T;
              soundSystem?: T;
            };
        kitchen?:
          | T
          | {
              fullKitchen?: T;
              dishwasher?: T;
              washingMachine?: T;
              dryer?: T;
              coffeeMachine?: T;
              oven?: T;
              microwave?: T;
              freezer?: T;
            };
        additional?:
          | T
          | {
              petsAllowed?: T;
              smokingAllowed?: T;
              wheelchairAccessible?: T;
              evCharger?: T;
              babyFriendly?: T;
              workDesk?: T;
              bicycles?: T;
              kayaks?: T;
            };
      };
  specialFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  rules?:
    | T
    | {
        checkInTime?: T;
        checkOutTime?: T;
        minStay?: T;
        maxStay?: T;
        houseRules?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  featuredImage?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  property?: T;
  name?: T;
  type?: T;
  startDate?: T;
  endDate?: T;
  pricing?:
    | T
    | {
        pricePerNight?: T;
        weekendPricing?:
          | T
          | {
              enabled?: T;
              fridayPrice?: T;
              saturdayPrice?: T;
              usePercentage?: T;
              weekendPercentage?: T;
            };
        cleaningFee?: T;
      };
  stayRules?:
    | T
    | {
        minStay?: T;
        maxStay?: T;
        allowedCheckInDays?: T;
      };
  color?: T;
  isActive?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocked-dates_select".
 */
export interface BlockedDatesSelect<T extends boolean = true> {
  property?: T;
  startDate?: T;
  endDate?: T;
  source?: T;
  reason?: T;
  notes?: T;
  icalData?:
    | T
    | {
        uid?: T;
        summary?: T;
        lastSynced?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ical-feeds_select".
 */
export interface IcalFeedsSelect<T extends boolean = true> {
  property?: T;
  isActive?: T;
  name?: T;
  platform?: T;
  direction?: T;
  importSettings?:
    | T
    | {
        importUrl?: T;
        syncFrequency?: T;
        autoBlockDates?: T;
      };
  exportSettings?:
    | T
    | {
        exportUrl?: T;
        includeBlockedDates?: T;
        includeBuffer?: T;
      };
  syncStatus?:
    | T
    | {
        lastSync?: T;
        lastSyncStatus?: T;
        lastSyncError?: T;
        eventsImported?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}